config/routes.rb
SistemaVigilancia::Application.routes.draw do
  
  devise_for :users

  resources :camaras

  scope '/admin' do
    resources :users
  end
  

  root :to => "camaras#index"
  #devise_scope :user do
  #	root to: "devise/sessions#new"
  #end

  resources :messages, only: [:index, :create]
  match "contact" => "messages#index"
  
end

app/models/camara.rb
class Camara < ActiveRecord::Base
  attr_accessible :ubicacion, :url

  has_and_belongs_to_many :users
end

app/models/message.rb
class Message < MailForm::Base
  attribute :name,          :validate => true
  attribute :email,         :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message_title, :validate => true
  attribute :message_body,  :validate => true

  def headers
    {
      :subject => "A message",
      :to => "fernando_sk8r_7@hotmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable :validatable, 

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable , :registerable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  #validates :password, confirmation: true
  #validates :password_confirmation, presence: true

  validates :email, :format => { :with => /\A(([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,}))?\z/i,
    :message => "debe seguir el formato ejemplo@midominio.com" }


  has_and_belongs_to_many :camaras
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/camaras_controller.rb
class CamarasController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  
  # GET /camaras
  # GET /camaras.json
  def index
    @camaras = Camara.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @camaras }
    end
  end

  # GET /camaras/1
  # GET /camaras/1.json
  def show
    @camara = Camara.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @camara }
    end
  end

  def show_one
    @camara = Camara.where(:url => params[:url])
    
    respond_to do |format|
      format.html
    end
    
  end

  # GET /camaras/new
  # GET /camaras/new.json
  def new
    @camara = Camara.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @camara }
    end
  end

  # GET /camaras/1/edit
  def edit
    @camara = Camara.find(params[:id])
  end

  # POST /camaras
  # POST /camaras.json
  def create
    @camara = Camara.new(params[:camara])

    respond_to do |format|
      if @camara.save

        admin = User.find(2)
        admin.camaras.push(@camara)

        format.html { redirect_to @camara, notice: 'Camara was successfully created.' }
        format.json { render json: @camara, status: :created, location: @camara }
      else
        format.html { render action: "new" }
        format.json { render json: @camara.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /camaras/1
  # PUT /camaras/1.json
  def update
    @camara = Camara.find(params[:id])

    respond_to do |format|
      if @camara.update_attributes(params[:camara])
        format.html { redirect_to @camara, notice: 'Camara was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @camara.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camaras/1
  # DELETE /camaras/1.json
  def destroy
    @camara = Camara.find(params[:id])
    @camara.destroy

    respond_to do |format|
      format.html { redirect_to camaras_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  respond_to :html

  def index
  end

  def create
    message = Message.new(params[:contact_form])
    if message.deliver
      redirect_to root_path, :notice => 'El email ha sido enviado.'
    else
      redirect_to root_path, :notice => 'El email no pudo ser enviado.'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @camaras = Camara.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @camaras = Camara.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @camaras = Camara.all
    camara_ids = params[:camara_ids] if params[:camara_ids] 
    camara_ids ||= []
    @user.camara_ids = camara_ids

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    @camaras = Camara.all
    camara_ids = params[:camara_ids] if params[:camara_ids] 
    camara_ids ||= []
    @user.camara_ids = camara_ids

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camaras_helper.rb
module CamarasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/camaras/_form.html.erb
<%= form_for @camara, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :ubicacion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ubicacion, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                camaras_path, :class => 'btn' %>
  </div>
<% end %>

app/views/camaras/edit.html.erb
<% if current_user && current_user.name == "Admin" %>
<%- model_class = Camara -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>
<% end %>

app/views/camaras/index.html.erb
<script type="text/javascript">

  function establecer_link(link) {
    $('#iframe').attr('src', link);
  }
  
</script>

<style type="text/css" media="screen">
  #img {
          background-image: url("assets/cam.jpg");
          background-repeat: no-repeat;
          background-position: top center;
          height: 500px;
        }
</style>

<% if current_user %>
<%- model_class = Camara -%>

<div class="span8">
  <h2> Mostrando </h2>
  <div class="page-header">
    <iframe id = "iframe" style="width: 1000; height: 600;" src="" frameborder="0" height="600" scrolling="no" width="700">cccc</iframe>
  </div>
</div>

<div class="span4">
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  </div>
  <%= link_to t('.new', :default => "Nueva cámara"),new_camara_path, :class => 'btn btn-primary' if current_user.name == "Admin"%>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:ubicacion) %></th>
        <% if current_user.name == "Admin" %>
          <th><%=t '.actions', :default => "Acciones" %></th>  
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% current_user.camaras.each do |camara| %>
        <tr>
          <td><%= link_to_function camara.ubicacion, "establecer_link('#{camara.url.to_s}');" %></td>
          <% if current_user.name == "Admin" %>
            <td>
              <%= link_to t('.edit', :default => "Editar"), edit_camara_path(camara), :class => 'btn btn-mini' %>
              <%= link_to "Eliminar", camara, :method => :delete, :data => { :confirm => 'Seguro deseas eliminar esta cámara?' }, :class => 'btn btn-mini btn-danger' %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
<div class="span3">
  <h1> <%= link_to "Iniciar sesión", new_user_session_path  %> </h1>
</div>

<div class="span9">
  <div id="img" class="page-header">
  </div>
</div>
<% end %>

app/views/camaras/new.html.erb
<% if current_user && current_user.name == "Admin" %>
<%- model_class = Camara -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>
<% end %>

app/views/camaras/show.html.erb
<% if current_user && current_user.name == "Admin" %>
<%- model_class = Camara -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ubicacion) %>:</strong></dt>
  <dd><%= @camara.ubicacion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @camara.url %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              camaras_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_camara_path(@camara), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              camara_path(@camara),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> 
  <title>SistemaVigilancia</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


  <script type="text/javascript" src="/plugins/datatables/media/js/jquery.js"></script>
  <script type="text/javascript" src="/plugins/datatables/media/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="/plugins/datatables/media/js/jquery.dataTables.min.js"></script>

  <link rel="stylesheet" type="text/css" href="/plugins/datatables/media/css/data_table.css" />

  <script type="text/javascript">
    $(document).ready(function() {
      $('#table').dataTable({
        "sPaginationType": "full_numbers",
        "bJQueryUI": true,
        "aoColumnDefs": [
          { "bSortable": false, "aTargets": [ -1 ] },
          { "bSearchable": false, "aTargets": [ -1 ]}
        ] } );



    });
  </script>
  
  

</head>
<body>

  <div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Sistema vigilancia</a>
      <div class="nav-collapse">
        <ul class="nav">
          <% if current_user %>
            <% if current_user.name == "Admin" %>
              <li><%= link_to "Mantener cámaras", camaras_path%></li>  
              <li><%= link_to "Crear cuenta", new_user_path %></li>
              <li><%= link_to "Agregar cámaras a cuentas", users_path %></li>
            <% else %>  
              <li><%= link_to "Ver cámaras"%></li>
              
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Contacto 
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li> <%= link_to "Contáctanos", "contact" %></li>
                  <li class="divider"></li>
                  <li> <%= link_to "Contacto Desarrolladores" %> </li>
                </ul>
              </li>

              
            <% end %>
          <% end %>

          <% if user_signed_in? %>
              <li style="color: skyblue;"> Bienvenido <%= current_user.name %> </li>
              <li> <%= link_to "Cerrar sesión",  destroy_user_session_path %> </li>
          <% else %>
              <li> <%= link_to "Iniciar sesión", new_user_session_path  %> </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  </div>



	

<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/messages/_message_form.html.erb
<%= form_for :contact_form, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">
    <%= f.label :Nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :titulo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :message_title, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :mensaje, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :message_body, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Enviar", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/messages/index.html.erb
<div class="page-header">
  <h1>Contáctenos</h1>
</div>
<%= render :partial => 'message_form' %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :repita_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password_confirmation, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit :Crear, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/_new_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count > 1 ? "#{@user.errors.count} errores." : "#{@user.errors.count} error." %> no se puede guardar el usuario:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :repita_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => 'text_field' %>
    </div>
  </div>

  <div class="line-forme">
    <div class="forme-lab">
      <label> 
        Cámaras
      </label>  
    </div>
  </div>

  <% @camaras.each do |camara| %>
    <div class="line-forme" style="margin-left:50px">
      <div class="forme-lab">

        <%= check_box_tag "camara_ids[]", camara.id, @user.camaras.member?(camara), :id => "CheckBox_#{camara.id}", :onclick => "checkBox_click(this)"-%>
        <%= h camara.ubicacion -%>
      </div> 
    </div>
  <% end %>
  
  <div class="form-actions">
    <%= f.submit :Crear, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if current_user && current_user.name == "Admin" %>
<%- model_class = User -%>
<div class="page-header">
  <h1>Editar</h1>
</div>
<%= render :partial => 'form' %>
<% end %>

app/views/users/index.html.erb
<% if current_user && current_user.name == "Admin" %>
<%- model_class = User -%>
<div class="page-header">
  <h1>Usuarios registrados</h1>
</div>

<table id="table" class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td>
          <%= link_to "Agregar cámara", edit_user_path(user), :class => 'btn btn-mini' %>
          <% if user.name != "Admin" %>
          <%= link_to "Borrar", user_path(user), :method => :delete, :data => { :confirm => "Seguro deseas borrar este usuario" }, :class => 'btn btn-mini btn-danger' %>
          <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/users/new.html.erb
<% if current_user && current_user.name == "Admin" %>
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'new_form' %>
<% end %>

app/views/users/show.html.erb
<% if current_user && current_user.name == "Admin" %>
<%- model_class = User -%>

<h1>Usuario</h1>


<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Nombre) %>:</strong></dt>
  <dd><%= @user.name %></dd>
</dl>

<div class="line-forme">
    <div class="forme-lab">
      <label> 
        Cámaras de <%= @user.name%>
      </label>  
    </div>
  </div>
  
  <table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:ubicacion) %></th>
    </tr>
  </thead>
  <tbody>
    <% @user.camaras.each do |camara| %>
      <tr>
        <td><%= @user.camaras.length == 0 ? "No posee cámaras registradas." : (link_to camara.ubicacion, camara_path(camara)) %></td>  
      </tr>
    <% end %>
  </tbody>
</table>
 

<div class="form-actions">
  <%= link_to "Atrás", users_path, :class => 'btn'  %>
  <%= link_to "Editar", edit_user_path(@user), :class => 'btn' %>
  <%= link_to "Eliminar", user_path(@user), :method => 'delete', :data => { :confirm => 'Está seguro que desea eliminar este usuario?'}, :class => 'btn btn-danger' %>
</div>
<% end %>